trigger:
- main

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'MCAPS-Support-REQ-75538-2024-pedromarques(b47f4b5c-a872-40c6-a011-01865fe9dd49)'
    appType: 'webApp'
    WebAppName: 'petedotnetwin'
    deployToSlotOrASE: true
    ResourceGroupName: 'pete_apps_win'
    SlotName: 'test'
    packageForLinux: 'D:/a/1/a/*.zip'
    enableCustomDeployment: true
    DeploymentType: 'zipDeploy'